deployment:
  tasks:
    - export DEPLOYPATH=/home/gils8669/public_html/
    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp favicon.ico $DEPLOYPATH
    - /bin/cp robot.txt $DEPLOYPATH
